### ISSUE TITLE
Spatial charts

### ISSUE THREAD

**Issue by dieghernan** [R-CoderDotCom/R-CHARTS#1]
Hi, 

Amazing resource, thank you for this. I have noticed that the "Spatial" section is under construction, if you consider take further steps on that I would be happy to help.

Some additional information about my background on this: I am the developer of [mapSpain](https://ropenspain.github.io/mapSpain/articles/articles/working_imagery.html), [giscoR](https://dieghernan.github.io/giscoR/index.html) and some other packages. I also have my own [rspatial](https://dieghernan.github.io/) blog, although is outdated. You can find several examples on the links.

Thank you

**Comment by R-CoderDotCom** [comment]
[Spatial charts](https://r-charts.com/spatial/) were added to the site! Thank you @dieghernan !
